<?php
require_once(getabspath("classes/cipherer.php"));




$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA = array();	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".truncateText"] = true;
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".NumberOfChars"] = 80; 
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".ShortName"] = "GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".OwnerID"] = "";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".OriginalTable"] = "t_facturas110";

//	field labels
$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA = array();
$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA = array();
$pageTitlesGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA = array();

if(mlang_getcurrentlang()=="Spanish")
{
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"] = array();
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"] = array();
	$pageTitlesGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"] = array();
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["id_func"] = "Id Func";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["id_func"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["gestion"] = "GESTIÓN";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["gestion"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["periodo"] = "PERIODO";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["periodo"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["mes_num"] = "N° MES";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["mes_num"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["monto_total"] = "MONTO TOTAL";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["monto_total"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["monto_13"] = "MONTO  13% ";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["monto_13"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["lugar"] = "LUGAR";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["lugar"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["fecha"] = "FECHA";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["fecha"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["name"] = "NOMBRE";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["name"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["l_name1"] = "APELLIDO PATERNO";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["l_name1"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["l_name2"] = "APELLIDO MATERNO";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["l_name2"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["ci"] = "CI";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["ci"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["expe"] = "EXP.";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["expe"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["unit"] = "UNIDAD";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["unit"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["dir_g"] = "DIRECCIÓN";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["dir_g"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["charge"] = "CARGO";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["charge"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["nit"] = "NIT";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]["nit"] = "";
	if (count($fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["Spanish"]))
		$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isUseToolTips"] = true;
}
if(mlang_getcurrentlang()=="")
{
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""] = array();
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""] = array();
	$pageTitlesGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""] = array();
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["id_func"] = "Id Func";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["id_func"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["gestion"] = "Gestion";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["gestion"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["periodo"] = "Periodo";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["periodo"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["mes_num"] = "Mes Num";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["mes_num"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["monto_total"] = "Monto Total";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["monto_total"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["monto_13"] = "Monto 13";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["monto_13"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["lugar"] = "Lugar";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["lugar"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["fecha"] = "Fecha";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["fecha"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["name"] = "Name";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["name"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["l_name1"] = "L Name1";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["l_name1"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["l_name2"] = "L Name2";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["l_name2"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["ci"] = "Ci";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["ci"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["expe"] = "Expe";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["expe"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["unit"] = "Unit";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["unit"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["dir_g"] = "Dir G";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["dir_g"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["charge"] = "Charge";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["charge"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["nit"] = "Nit";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]["nit"] = "";
	if (count($fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[""]))
		$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isUseToolTips"] = true;
}
if(mlang_getcurrentlang()=="English")
{
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"] = array();
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"] = array();
	$pageTitlesGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"] = array();
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["id_func"] = "Id Func";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["id_func"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["gestion"] = "Gestion";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["gestion"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["periodo"] = "Periodo";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["periodo"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["mes_num"] = "Mes Num";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["mes_num"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["monto_total"] = "Monto Total";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["monto_total"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["monto_13"] = "Monto 13";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["monto_13"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["lugar"] = "Lugar";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["lugar"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["fecha"] = "Fecha";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["fecha"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["name"] = "Name";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["name"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["l_name1"] = "L Name1";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["l_name1"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["l_name2"] = "L Name2";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["l_name2"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["ci"] = "Ci";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["ci"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["expe"] = "Expe";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["expe"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["unit"] = "Unit";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["unit"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["dir_g"] = "Dir G";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["dir_g"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["charge"] = "Charge";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["charge"] = "";
	$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["nit"] = "Nit";
	$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]["nit"] = "";
	if (count($fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["English"]))
		$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isUseToolTips"] = true;
}
	
	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".NCSearch"] = true;



$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".shortTableName"] = "GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".nSecOptions"] = 0;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".recsPerRowList"] = 1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".recsPerRowPrint"] = 1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".mainTableOwnerID"] = "";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".moveNext"] = 1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".entityType"] = 2;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".strOriginalTableName"] = "t_facturas110";




$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".showAddInPopup"] = false;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".showEditInPopup"] = false;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".showViewInPopup"] = false;

//page's base css files names
$popupPagesLayoutNames = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".popupPagesLayoutNames"] = $popupPagesLayoutNames;


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".fieldsForRegister"] = array();

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listAjax"] = false;

	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".audit"] = false;

	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".locking"] = false;


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".add"] = true;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".afterAddAction"] = 1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".closePopupAfterAdd"] = 1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".afterAddActionDetTable"] = "";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".list"] = true;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAdd"] = true;


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportTo"] = true;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFriendly"] = true;


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".showSimpleSearchOptions"] = false;

// search Saving settings
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".searchSaving"] = false;
//

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".showSearchPanel"] = true;
		$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".flexibleSearch"] = true;		

if (isMobile())
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isUseAjaxSuggest"] = false;
else 
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isUseAjaxSuggest"] = true;




$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addPageEvents"] = false;

// use timepicker for search panel
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isUseTimeForSearch"] = false;





$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".filterFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".requiredSearchFields"] = array();

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "id_func";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "name";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "l_name1";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "l_name2";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "ci";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "expe";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "unit";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "dir_g";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "charge";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "nit";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "gestion";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "periodo";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "mes_num";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "monto_total";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "monto_13";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "lugar";
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".allSearchFields"][] = "fecha";
	

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".googleLikeFields"][] = "fecha";


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".advSearchFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".tableType"] = "report";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printerPageOrientation"] = 0;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".nPrinterPageScale"] = 100;





$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".geocodingEnabled"] = false;

//report settings
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printReportLayout"] = 6;	

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".reportPrintPartitionType"] = 0;	
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".reportPrintGroupsPerPage"] = 40;	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".lowGroup"] = 0;



$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".pageSize"] = 20;	




$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".reportPageSummary"] = true;


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".repShowDet"] = true;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".reportLayout"] = 6;

//end of report settings



	





// view page pdf

// print page pdf
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".isPrinterPagePDF"] = true;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".nPrinterPagePDFScale"] = 100;



$tstrOrderBy = "";
if(strlen($tstrOrderBy) && strtolower(substr($tstrOrderBy,0,8))!="order by")
	$tstrOrderBy = "order by ".$tstrOrderBy;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".strOrderBy"] = $tstrOrderBy;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".orderindexes"] = array();

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".sqlHead"] = "SELECT funcionario.id_func,  funcionario.name,  funcionario.l_name1,  funcionario.l_name2,  funcionario.ci,  funcionario.expe,  char_per.unit,  char_per.dir_g,  char_per.charge,  funcionario.nit,  t_facturas110.gestion,  t_facturas110.periodo,  t_facturas110.mes_num,  t_facturas110.monto_total,  t_facturas110.monto_13,  t_facturas110.lugar,  t_facturas110.fecha";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".sqlFrom"] = "FROM t_facturas110  INNER JOIN funcionario ON t_facturas110.id_func = funcionario.id_func  INNER JOIN char_per ON funcionario.id_func = char_per.id_per";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".sqlWhereExpr"] = "";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".sqlTail"] = "";









//fill array of records per page for list and report without group fields
$arrRPP = array();
$arrRPP[] = 10;
$arrRPP[] = 20;
$arrRPP[] = 30;
$arrRPP[] = 50;
$arrRPP[] = 100;
$arrRPP[] = 500;
$arrRPP[] = -1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".arrRecsPerPage"] = $arrRPP;

//fill array of groups per page for report with group fields
$arrGPP = array();
$arrGPP[] = 1;
$arrGPP[] = 3;
$arrGPP[] = 5;
$arrGPP[] = 10;
$arrGPP[] = 50;
$arrGPP[] = 100;
$arrGPP[] = -1;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".arrGroupsPerPage"] = $arrGPP;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".highlightSearchResults"] = true;

$tableKeysGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".Keys"] = $tableKeysGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA;

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".listFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".hideMobileList"] = array();


$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".viewFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".addFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".masterListFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineAddFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".editFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".inlineEditFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".exportFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".importFields"][] = "fecha";

$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"] = array();
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "id_func";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "name";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "l_name1";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "l_name2";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "ci";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "expe";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "unit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "dir_g";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "charge";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "nit";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "gestion";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "periodo";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "mes_num";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "monto_total";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "monto_13";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "lugar";
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".printFields"][] = "fecha";

//	id_func
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 1;
	$fdata["strName"] = "id_func";
	$fdata["GoodName"] = "id_func";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","id_func"); 
	$fdata["FieldType"] = 3;
	
		// report field settings
					// end of report field settings
	
		$fdata["AutoInc"] = true;
	
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "id_func"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.id_func";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "number";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
				$edata["validateAs"]["basicValidate"][] = getJsValidatorName("Number");	
								
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Equals", "More than", "Less than", "Between");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["id_func"] = $fdata;
//	name
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 2;
	$fdata["strName"] = "name";
	$fdata["GoodName"] = "name";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","name"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "name"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.name";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["name"] = $fdata;
//	l_name1
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 3;
	$fdata["strName"] = "l_name1";
	$fdata["GoodName"] = "l_name1";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","l_name1"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "l_name1"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.l_name1";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["l_name1"] = $fdata;
//	l_name2
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 4;
	$fdata["strName"] = "l_name2";
	$fdata["GoodName"] = "l_name2";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","l_name2"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "l_name2"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.l_name2";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["l_name2"] = $fdata;
//	ci
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 5;
	$fdata["strName"] = "ci";
	$fdata["GoodName"] = "ci";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","ci"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "ci"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.ci";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["ci"] = $fdata;
//	expe
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 6;
	$fdata["strName"] = "expe";
	$fdata["GoodName"] = "expe";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","expe"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "expe"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.expe";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["expe"] = $fdata;
//	unit
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 7;
	$fdata["strName"] = "unit";
	$fdata["GoodName"] = "unit";
	$fdata["ownerTable"] = "char_per";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","unit"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "unit"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "char_per.unit";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["unit"] = $fdata;
//	dir_g
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 8;
	$fdata["strName"] = "dir_g";
	$fdata["GoodName"] = "dir_g";
	$fdata["ownerTable"] = "char_per";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","dir_g"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "dir_g"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "char_per.dir_g";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["dir_g"] = $fdata;
//	charge
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 9;
	$fdata["strName"] = "charge";
	$fdata["GoodName"] = "charge";
	$fdata["ownerTable"] = "char_per";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","charge"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "charge"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "char_per.charge";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["charge"] = $fdata;
//	nit
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 10;
	$fdata["strName"] = "nit";
	$fdata["GoodName"] = "nit";
	$fdata["ownerTable"] = "funcionario";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","nit"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		
		
		
		
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "nit"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "funcionario.nit";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["nit"] = $fdata;
//	gestion
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 11;
	$fdata["strName"] = "gestion";
	$fdata["GoodName"] = "gestion";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","gestion"); 
	$fdata["FieldType"] = 2;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "gestion"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.gestion";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Readonly");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
		
		
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
								
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Equals", "More than", "Less than", "Between");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["gestion"] = $fdata;
//	periodo
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 12;
	$fdata["strName"] = "periodo";
	$fdata["GoodName"] = "periodo";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","periodo"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "periodo"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.periodo";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Readonly");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
		
		
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["periodo"] = $fdata;
//	mes_num
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 13;
	$fdata["strName"] = "mes_num";
	$fdata["GoodName"] = "mes_num";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","mes_num"); 
	$fdata["FieldType"] = 3;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "mes_num"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.mes_num";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Readonly");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
		
		
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
								
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Equals", "More than", "Less than", "Between");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["mes_num"] = $fdata;
//	monto_total
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 14;
	$fdata["strName"] = "monto_total";
	$fdata["GoodName"] = "monto_total";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","monto_total"); 
	$fdata["FieldType"] = 14;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "monto_total"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.monto_total";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "Number");
	
		
		
		
		
		
		
		$vdata["DecimalDigits"] = 2;
	
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		$edata["IsRequired"] = true; 
	
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "number";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
				$edata["validateAs"]["basicValidate"][] = getJsValidatorName("Number");	
						$edata["validateAs"]["basicValidate"][] = "IsRequired";
			
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Equals", "More than", "Less than", "Between");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["monto_total"] = $fdata;
//	monto_13
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 15;
	$fdata["strName"] = "monto_13";
	$fdata["GoodName"] = "monto_13";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","monto_13"); 
	$fdata["FieldType"] = 3;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "monto_13"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.monto_13";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		$edata["IsRequired"] = true; 
	
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "number";
	
		$edata["EditParams"] = "";
			
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
				$edata["validateAs"]["basicValidate"][] = getJsValidatorName("Number");	
						$edata["validateAs"]["basicValidate"][] = "IsRequired";
			
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Equals", "More than", "Less than", "Between");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["monto_13"] = $fdata;
//	lugar
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 16;
	$fdata["strName"] = "lugar";
	$fdata["GoodName"] = "lugar";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","lugar"); 
	$fdata["FieldType"] = 200;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "lugar"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.lugar";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Text field");
	
			
	
	


		
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		
		
			$edata["HTML5InuptType"] = "text";
	
		$edata["EditParams"] = "";
			$edata["EditParams"].= " maxlength=20";
	
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
		
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Contains", "Equals", "Empty");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["lugar"] = $fdata;
//	fecha
//	Custom field settings
	$fdata = array();
	$fdata["Index"] = 17;
	$fdata["strName"] = "fecha";
	$fdata["GoodName"] = "fecha";
	$fdata["ownerTable"] = "t_facturas110";
	$fdata["Label"] = GetFieldLabel("GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA","fecha"); 
	$fdata["FieldType"] = 7;
	
		// report field settings
					// end of report field settings
	
		
		
				
		$fdata["bListPage"] = true; 
	
		$fdata["bAddPage"] = true; 
	
		$fdata["bInlineAdd"] = true; 
	
		$fdata["bEditPage"] = true; 
	
		$fdata["bInlineEdit"] = true; 
	
		$fdata["bViewPage"] = true; 
	
		$fdata["bAdvancedSearch"] = true; 
	
		$fdata["bPrinterPage"] = true; 
	
		$fdata["bExportPage"] = true; 
	
		$fdata["strField"] = "fecha"; 
	
		$fdata["isSQLExpression"] = true;
	$fdata["FullName"] = "t_facturas110.fecha";
	
		
		
				$fdata["FieldPermissions"] = true;
	
				$fdata["UploadFolder"] = "files";
		
//  Begin View Formats
	$fdata["ViewFormats"] = array();
	
	$vdata = array("ViewFormat" => "Short Date");
	
		
		
		
		
		
		
		
		
		
		
		
		$vdata["NeedEncode"] = true;
	
	$fdata["ViewFormats"]["report"] = $vdata;
//  End View Formats

//	Begin Edit Formats 	
	$fdata["EditFormats"] = array();
	
	$edata = array("EditFormat" => "Date");
	
			
	
	


		$edata["IsRequired"] = true; 
	
		
		
		
			$edata["acceptFileTypes"] = ".+$";
	
		$edata["maxNumberOfFiles"] = 1;
	
		
		
		$edata["DateEditType"] = 2; 
	$edata["InitialYearFactor"] = 100; 
	$edata["LastYearFactor"] = 10; 
	
		
		
		
		$edata["controlWidth"] = 200;
	
//	Begin validation
	$edata["validateAs"] = array();
	$edata["validateAs"]["basicValidate"] = array();
	$edata["validateAs"]["customMessages"] = array();
						$edata["validateAs"]["basicValidate"][] = "IsRequired";
			
		
	//	End validation
	
		
		
		
	
		
	$fdata["EditFormats"]["search"] = $edata;
//	End Edit Formats
	
	
	$fdata["isSeparate"] = false;
	
	
	
	
// the field's search options settings
		
			// the default search options list
				$fdata["searchOptionsList"] = array("Equals", "More than", "Less than", "Between");
// the end of search options settings	

	

	
	$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA["fecha"] = $fdata;

	
$tables_data["GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"]=&$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA;
$field_labels["GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA"] = &$fieldLabelsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA;
$fieldToolTips["GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"] = &$fieldToolTipsGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA;
$page_titles["GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA"] = &$pageTitlesGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA;

// -----------------start  prepare master-details data arrays ------------------------------//
// tables which are detail tables for current table (master)
$detailsTablesData["GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"] = array();
	
// tables which are master tables for current table (detail)
$masterTablesData["GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"] = array();


// -----------------end  prepare master-details data arrays ------------------------------//

require_once(getabspath("classes/sql.php"));










function createSqlQuery_GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA()
{
$proto0=array();
$proto0["m_strHead"] = "SELECT";
$proto0["m_strFieldList"] = "funcionario.id_func,  funcionario.name,  funcionario.l_name1,  funcionario.l_name2,  funcionario.ci,  funcionario.expe,  char_per.unit,  char_per.dir_g,  char_per.charge,  funcionario.nit,  t_facturas110.gestion,  t_facturas110.periodo,  t_facturas110.mes_num,  t_facturas110.monto_total,  t_facturas110.monto_13,  t_facturas110.lugar,  t_facturas110.fecha";
$proto0["m_strFrom"] = "FROM t_facturas110  INNER JOIN funcionario ON t_facturas110.id_func = funcionario.id_func  INNER JOIN char_per ON funcionario.id_func = char_per.id_per";
$proto0["m_strWhere"] = "";
$proto0["m_strOrderBy"] = "";
$proto0["m_strTail"] = "";
			$proto0["cipherer"] = null;
$proto1=array();
$proto1["m_sql"] = "";
$proto1["m_uniontype"] = "SQLL_UNKNOWN";
	$obj = new SQLNonParsed(array(
	"m_sql" => ""
));

$proto1["m_column"]=$obj;
$proto1["m_contained"] = array();
$proto1["m_strCase"] = "";
$proto1["m_havingmode"] = false;
$proto1["m_inBrackets"] = false;
$proto1["m_useAlias"] = false;
$obj = new SQLLogicalExpr($proto1);

$proto0["m_where"] = $obj;
$proto3=array();
$proto3["m_sql"] = "";
$proto3["m_uniontype"] = "SQLL_UNKNOWN";
	$obj = new SQLNonParsed(array(
	"m_sql" => ""
));

$proto3["m_column"]=$obj;
$proto3["m_contained"] = array();
$proto3["m_strCase"] = "";
$proto3["m_havingmode"] = false;
$proto3["m_inBrackets"] = false;
$proto3["m_useAlias"] = false;
$obj = new SQLLogicalExpr($proto3);

$proto0["m_having"] = $obj;
$proto0["m_fieldlist"] = array();
						$proto5=array();
			$obj = new SQLField(array(
	"m_strName" => "id_func",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto5["m_sql"] = "funcionario.id_func";
$proto5["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto5["m_expr"]=$obj;
$proto5["m_alias"] = "";
$obj = new SQLFieldListItem($proto5);

$proto0["m_fieldlist"][]=$obj;
						$proto7=array();
			$obj = new SQLField(array(
	"m_strName" => "name",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto7["m_sql"] = "funcionario.name";
$proto7["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto7["m_expr"]=$obj;
$proto7["m_alias"] = "";
$obj = new SQLFieldListItem($proto7);

$proto0["m_fieldlist"][]=$obj;
						$proto9=array();
			$obj = new SQLField(array(
	"m_strName" => "l_name1",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto9["m_sql"] = "funcionario.l_name1";
$proto9["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto9["m_expr"]=$obj;
$proto9["m_alias"] = "";
$obj = new SQLFieldListItem($proto9);

$proto0["m_fieldlist"][]=$obj;
						$proto11=array();
			$obj = new SQLField(array(
	"m_strName" => "l_name2",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto11["m_sql"] = "funcionario.l_name2";
$proto11["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto11["m_expr"]=$obj;
$proto11["m_alias"] = "";
$obj = new SQLFieldListItem($proto11);

$proto0["m_fieldlist"][]=$obj;
						$proto13=array();
			$obj = new SQLField(array(
	"m_strName" => "ci",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto13["m_sql"] = "funcionario.ci";
$proto13["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto13["m_expr"]=$obj;
$proto13["m_alias"] = "";
$obj = new SQLFieldListItem($proto13);

$proto0["m_fieldlist"][]=$obj;
						$proto15=array();
			$obj = new SQLField(array(
	"m_strName" => "expe",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto15["m_sql"] = "funcionario.expe";
$proto15["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto15["m_expr"]=$obj;
$proto15["m_alias"] = "";
$obj = new SQLFieldListItem($proto15);

$proto0["m_fieldlist"][]=$obj;
						$proto17=array();
			$obj = new SQLField(array(
	"m_strName" => "unit",
	"m_strTable" => "char_per",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto17["m_sql"] = "char_per.unit";
$proto17["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto17["m_expr"]=$obj;
$proto17["m_alias"] = "";
$obj = new SQLFieldListItem($proto17);

$proto0["m_fieldlist"][]=$obj;
						$proto19=array();
			$obj = new SQLField(array(
	"m_strName" => "dir_g",
	"m_strTable" => "char_per",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto19["m_sql"] = "char_per.dir_g";
$proto19["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto19["m_expr"]=$obj;
$proto19["m_alias"] = "";
$obj = new SQLFieldListItem($proto19);

$proto0["m_fieldlist"][]=$obj;
						$proto21=array();
			$obj = new SQLField(array(
	"m_strName" => "charge",
	"m_strTable" => "char_per",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto21["m_sql"] = "char_per.charge";
$proto21["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto21["m_expr"]=$obj;
$proto21["m_alias"] = "";
$obj = new SQLFieldListItem($proto21);

$proto0["m_fieldlist"][]=$obj;
						$proto23=array();
			$obj = new SQLField(array(
	"m_strName" => "nit",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto23["m_sql"] = "funcionario.nit";
$proto23["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto23["m_expr"]=$obj;
$proto23["m_alias"] = "";
$obj = new SQLFieldListItem($proto23);

$proto0["m_fieldlist"][]=$obj;
						$proto25=array();
			$obj = new SQLField(array(
	"m_strName" => "gestion",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto25["m_sql"] = "t_facturas110.gestion";
$proto25["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto25["m_expr"]=$obj;
$proto25["m_alias"] = "";
$obj = new SQLFieldListItem($proto25);

$proto0["m_fieldlist"][]=$obj;
						$proto27=array();
			$obj = new SQLField(array(
	"m_strName" => "periodo",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto27["m_sql"] = "t_facturas110.periodo";
$proto27["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto27["m_expr"]=$obj;
$proto27["m_alias"] = "";
$obj = new SQLFieldListItem($proto27);

$proto0["m_fieldlist"][]=$obj;
						$proto29=array();
			$obj = new SQLField(array(
	"m_strName" => "mes_num",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto29["m_sql"] = "t_facturas110.mes_num";
$proto29["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto29["m_expr"]=$obj;
$proto29["m_alias"] = "";
$obj = new SQLFieldListItem($proto29);

$proto0["m_fieldlist"][]=$obj;
						$proto31=array();
			$obj = new SQLField(array(
	"m_strName" => "monto_total",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto31["m_sql"] = "t_facturas110.monto_total";
$proto31["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto31["m_expr"]=$obj;
$proto31["m_alias"] = "";
$obj = new SQLFieldListItem($proto31);

$proto0["m_fieldlist"][]=$obj;
						$proto33=array();
			$obj = new SQLField(array(
	"m_strName" => "monto_13",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto33["m_sql"] = "t_facturas110.monto_13";
$proto33["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto33["m_expr"]=$obj;
$proto33["m_alias"] = "";
$obj = new SQLFieldListItem($proto33);

$proto0["m_fieldlist"][]=$obj;
						$proto35=array();
			$obj = new SQLField(array(
	"m_strName" => "lugar",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto35["m_sql"] = "t_facturas110.lugar";
$proto35["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto35["m_expr"]=$obj;
$proto35["m_alias"] = "";
$obj = new SQLFieldListItem($proto35);

$proto0["m_fieldlist"][]=$obj;
						$proto37=array();
			$obj = new SQLField(array(
	"m_strName" => "fecha",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto37["m_sql"] = "t_facturas110.fecha";
$proto37["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto37["m_expr"]=$obj;
$proto37["m_alias"] = "";
$obj = new SQLFieldListItem($proto37);

$proto0["m_fieldlist"][]=$obj;
$proto0["m_fromlist"] = array();
												$proto39=array();
$proto39["m_link"] = "SQLL_MAIN";
			$proto40=array();
$proto40["m_strName"] = "t_facturas110";
$proto40["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto40["m_columns"] = array();
$proto40["m_columns"][] = "id_fac";
$proto40["m_columns"][] = "id_func";
$proto40["m_columns"][] = "gestion";
$proto40["m_columns"][] = "periodo";
$proto40["m_columns"][] = "mes_num";
$proto40["m_columns"][] = "monto_total";
$proto40["m_columns"][] = "monto_13";
$proto40["m_columns"][] = "lugar";
$proto40["m_columns"][] = "fecha";
$proto40["m_columns"][] = "archivo_digital";
$obj = new SQLTable($proto40);

$proto39["m_table"] = $obj;
$proto39["m_sql"] = "t_facturas110";
$proto39["m_alias"] = "";
$proto39["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto41=array();
$proto41["m_sql"] = "";
$proto41["m_uniontype"] = "SQLL_UNKNOWN";
	$obj = new SQLNonParsed(array(
	"m_sql" => ""
));

$proto41["m_column"]=$obj;
$proto41["m_contained"] = array();
$proto41["m_strCase"] = "";
$proto41["m_havingmode"] = false;
$proto41["m_inBrackets"] = false;
$proto41["m_useAlias"] = false;
$obj = new SQLLogicalExpr($proto41);

$proto39["m_joinon"] = $obj;
$obj = new SQLFromListItem($proto39);

$proto0["m_fromlist"][]=$obj;
												$proto43=array();
$proto43["m_link"] = "SQLL_INNERJOIN";
			$proto44=array();
$proto44["m_strName"] = "funcionario";
$proto44["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto44["m_columns"] = array();
$proto44["m_columns"][] = "id_func";
$proto44["m_columns"][] = "estado";
$proto44["m_columns"][] = "name";
$proto44["m_columns"][] = "l_name1";
$proto44["m_columns"][] = "l_name2";
$proto44["m_columns"][] = "l_name_es";
$proto44["m_columns"][] = "nationality";
$proto44["m_columns"][] = "nati";
$proto44["m_columns"][] = "ci";
$proto44["m_columns"][] = "expe";
$proto44["m_columns"][] = "afp";
$proto44["m_columns"][] = "nua";
$proto44["m_columns"][] = "c_status";
$proto44["m_columns"][] = "sex";
$proto44["m_columns"][] = "g_blood";
$proto44["m_columns"][] = "p_email";
$proto44["m_columns"][] = "job_email";
$proto44["m_columns"][] = "adress";
$proto44["m_columns"][] = "place_res";
$proto44["m_columns"][] = "phone_num";
$proto44["m_columns"][] = "cel_num";
$proto44["m_columns"][] = "phone_job";
$proto44["m_columns"][] = "p1_born";
$proto44["m_columns"][] = "p2_born";
$proto44["m_columns"][] = "p3_born";
$proto44["m_columns"][] = "date_born";
$proto44["m_columns"][] = "lic_driv";
$proto44["m_columns"][] = "type_lic";
$proto44["m_columns"][] = "prof";
$proto44["m_columns"][] = "col_prof";
$proto44["m_columns"][] = "num_prof";
$proto44["m_columns"][] = "nit";
$proto44["m_columns"][] = "on_off";
$proto44["m_columns"][] = "last_gra";
$proto44["m_columns"][] = "cole";
$proto44["m_columns"][] = "ciudad_de";
$proto44["m_columns"][] = "anyo_de";
$proto44["m_columns"][] = "title";
$proto44["m_columns"][] = "nro_libreta";
$proto44["m_columns"][] = "matricula";
$proto44["m_columns"][] = "anyo";
$proto44["m_columns"][] = "tipo_libreta";
$proto44["m_columns"][] = "nro_referencia1";
$proto44["m_columns"][] = "nro_referencia2";
$proto44["m_columns"][] = "es_estudiante";
$proto44["m_columns"][] = "nombre_carrera";
$proto44["m_columns"][] = "especialidad";
$proto44["m_columns"][] = "ultimo_anyo";
$proto44["m_columns"][] = "foto";
$proto44["m_columns"][] = "updated_at";
$proto44["m_columns"][] = "created_at";
$obj = new SQLTable($proto44);

$proto43["m_table"] = $obj;
$proto43["m_sql"] = "INNER JOIN funcionario ON t_facturas110.id_func = funcionario.id_func";
$proto43["m_alias"] = "";
$proto43["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto45=array();
$proto45["m_sql"] = "t_facturas110.id_func = funcionario.id_func";
$proto45["m_uniontype"] = "SQLL_UNKNOWN";
						$obj = new SQLField(array(
	"m_strName" => "id_func",
	"m_strTable" => "t_facturas110",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto45["m_column"]=$obj;
$proto45["m_contained"] = array();
$proto45["m_strCase"] = "= funcionario.id_func";
$proto45["m_havingmode"] = false;
$proto45["m_inBrackets"] = false;
$proto45["m_useAlias"] = false;
$obj = new SQLLogicalExpr($proto45);

$proto43["m_joinon"] = $obj;
$obj = new SQLFromListItem($proto43);

$proto0["m_fromlist"][]=$obj;
												$proto47=array();
$proto47["m_link"] = "SQLL_INNERJOIN";
			$proto48=array();
$proto48["m_strName"] = "char_per";
$proto48["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto48["m_columns"] = array();
$proto48["m_columns"][] = "id_char_per";
$proto48["m_columns"][] = "id_per";
$proto48["m_columns"][] = "dir_g";
$proto48["m_columns"][] = "unit";
$proto48["m_columns"][] = "area";
$proto48["m_columns"][] = "boss_is";
$proto48["m_columns"][] = "boss_ij";
$proto48["m_columns"][] = "charge";
$proto48["m_columns"][] = "date_des";
$proto48["m_columns"][] = "date_end";
$proto48["m_columns"][] = "num_memo";
$proto48["m_columns"][] = "date_des_ini";
$obj = new SQLTable($proto48);

$proto47["m_table"] = $obj;
$proto47["m_sql"] = "INNER JOIN char_per ON funcionario.id_func = char_per.id_per";
$proto47["m_alias"] = "";
$proto47["m_srcTableName"] = "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";
$proto49=array();
$proto49["m_sql"] = "funcionario.id_func = char_per.id_per";
$proto49["m_uniontype"] = "SQLL_UNKNOWN";
						$obj = new SQLField(array(
	"m_strName" => "id_func",
	"m_strTable" => "funcionario",
	"m_srcTableName" => "GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"
));

$proto49["m_column"]=$obj;
$proto49["m_contained"] = array();
$proto49["m_strCase"] = "= char_per.id_per";
$proto49["m_havingmode"] = false;
$proto49["m_inBrackets"] = false;
$proto49["m_useAlias"] = false;
$obj = new SQLLogicalExpr($proto49);

$proto47["m_joinon"] = $obj;
$obj = new SQLFromListItem($proto47);

$proto0["m_fromlist"][]=$obj;
$proto0["m_groupby"] = array();
$proto0["m_orderby"] = array();
$proto0["m_srcTableName"]="GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA";		
$obj = new SQLQuery($proto0);

	return $obj;
}
$queryData_GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA = createSqlQuery_GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA();


	
																	
	
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".sqlquery"] = $queryData_GENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA;

$tableEvents["GENERACIÓN DEL PERSONAL QUE PRESENTA FACTURAS PARA LA RETENCIÓN IMPOSITIVA"] = new eventsBase;
$tdataGENERACI_N_DEL_PERSONAL_QUE_PRESENTA_FACTURAS_PARA_LA_RETENCI_N_IMPOSITIVA[".hasEvents"] = false;

?>